name: my_messengers
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/mm-terekhin/flutter_my_messengers.git
repository: https://github.com/pavelzaichyk/flutter_unity_ads

environment:
  sdk: ^3.5.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mm_terekhin.my_messengers
        pluginClass: MyMessengersPlugin
      ios:
        pluginClass: MyMessengersPlugin